// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindowsFormExam.Data;

#nullable disable

namespace WindowsFormExam.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240406173758_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WindowsFormExam.Entities.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ending_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("ToDoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 4, 6, 20, 37, 58, 154, DateTimeKind.Local).AddTicks(6836),
                            Description = "Pass an exam",
                            EndingDate = new DateTime(2024, 4, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Win Forms Exam"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 4, 6, 20, 37, 58, 154, DateTimeKind.Local).AddTicks(6913),
                            Description = "Just testing todo)",
                            EndingDate = new DateTime(2024, 4, 6, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Test Todo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
